# This file was generated by GoReleaser. DO NOT EDIT.
class Isaka < Formula
  desc "tail log for Apache Kafka"
  homepage "https://github.com/pyama86/isaka"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pyama86/isaka/releases/download/v0.0.3/isaka_0.0.3_darwin_amd64.tar.gz"
    sha256 "12938945d2787206a0890adcbe9ec135d4cd4a5d29fb3b043ea9e14d69b08ef2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/isaka/releases/download/v0.0.3/isaka_0.0.3_linux_amd64.tar.gz"
      sha256 "543ca198308ab4f96464db14a6c505ab803ae8e70a99417ecfe426679fccac91"
    end
  end

  def install
    bin.install Dir['isaka']
  end

  test do
    system "#{bin}/isaka"
  end
end
