# This file was generated by GoReleaser. DO NOT EDIT.
class Isaka < Formula
  desc "Simple command-line snippet manager"
  homepage "https://github.com/pyama86/isaka"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pyama86/isaka/releases/download/v0.0.2/isaka_0.0.2_darwin_amd64.tar.gz"
    sha256 "b38a43f4b9ad86f66c5e58b3f25ed2fb86063ae8f2549a76c35e31a3a7a9dd8f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/isaka/releases/download/v0.0.2/isaka_0.0.2_linux_amd64.tar.gz"
      sha256 "84f1cc40b7eae6823a04eee9588415ed21ddfe43c617d6dc884147d2cd0e94b9"
    end
  end

  def install
    bin.install Dir['isaka']
  end

  test do
    system "#{bin}/isaka"
  end
end
